name: deploy website
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@master
        with:
          vercel-cli: vercel
          vercel-args: '--prod'
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID_DEV}}
          github-token: ${{ secrets.GITHUB_TOKEN }}
